name: 05 - 1 - Event Filters and Activity Types

on:
  pull_request:
    types: 
      - closed
      - synchronize
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-lateset
    steps:
      - run: echo "Running whever a PR is closed"