name: 16 - Working with Environments
run-name: 16 - Working with Environemnts | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
  
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
      my-env-value: ${{vars.MY_ENV_VALUE || 'default version'}}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable ${{env.my-env-value}}}"